### ISSUE TITLE
Don't need -S when read old.bam?

### ISSUE THREAD

**Issue by xigyou** [timothyjamesbecker/SVE#1]
phred64to33.py
used as: samtools view -Sh old.bam | SVE/stages/utils/phred64to33.py | samtools view -Sb - > ./phred33.bam

Don't need -S when read old.bam?

should be
used as: samtools view -h old.bam | SVE/stages/utils/phred64to33.py | samtools view -Sb - > ./phred33.bam

**Comment by timothyjamesbecker** [comment]
usage is a comment and is included just to show that this tool is meant to be piped.  -S which is the auto-sense might now be option in the current samtools.
