### ISSUE TITLE
Targets option for step 2 in advanced mode

### ISSUE THREAD

**Issue by kyleLesack** [timothyjamesbecker/SVE#10]
Hello,

I would like to use SVE/FusorSV for calling structural variants in some _C. elegans_ data that I'm working with. Could you please clarify how to use to targets option or point me towards the correct documentation? 

Also, regarding the FusorSV manual mentioned in the SVE documention (see below), are you just referring to the FusorSV repo's documentation (https://github.com/timothyjamesbecker/FusorSV)? I wasn't able to find the targets option instructions there.

> -t or -targets option is used for target assembly for in silico SV callng validation or SV calling breakpoint refinement. This step is recommened after all calling is completed and the step (3) FusorSV data fusion and arbitration step has produce SV calls for each sample which will be passed to this -t argument. See the FusorSV manual for more information.

Thanks in advance!

**Comment by timothyjamesbecker** [comment]
I will have to revisit the documentation for the target option.  The targets option is when you wish to use SVE and FusorSV with targeted assembly via TIGRASV.  This will provide more accurate breakpoints and high confidence in those calls that TIGRASV can assemble.

**Comment by kyleLesack** [comment]
Thanks. I did manage to figure it out by looking through your source code. It worked after I pointed it to the Breakdancer vcf and calls files.

**Comment by timothyjamesbecker** [comment]
And of course, you can use first pass FusorSV calls as well.

**Comment by kyleLesack** [comment]
Thanks for the tip. I was passing both a .calls and .vcf file to Tigra. Will it work with just a .vcf file (I'm not seeing a .calls file in the FusorSV output)?

**Comment by timothyjamesbecker** [comment]
It will work with FusorSV vcf calls the BD.call files and the BD vcf calls
that the SVE converts from .call format. The FusorSV calls have less false
positives so the runtime is greatly reduced compared to BD in human data.
FOr humans this target assembly step can take up a day to run on a human
for FusorSV vcf and up to a week on BD calls.
