### ISSUE TITLE
Accounting for tools that compare across samples

### ISSUE THREAD

**Issue by lauracottino** [timothyjamesbecker/SVE#11]
Hi, I know that some of the SV callers (GenomeSTRiP for example) detect variation using data from multiple individuals/comparison across multiple samples. Does SVE account for this or does it run a single samples at a time through each tool even if a list of multiple BAMs is given as the input? Thanks.

**Comment by timothyjamesbecker** [comment]
SVE is designed. to simplify the process of SV calling as as as to unify the output for all VCF.  It has been designed to process all of the callers for one sample a time (which is very time consuming).  To speed that up, you can use a machine per sample such as was used for the FusorSV paper using a cluster (27 systems at once using the higher level qsub script in the SVE/script folder).  If speed is not your concern and you have a lot of time on your hands, you can provide a list of BAMs to variant_processor.py and it will run one caller at a time on each sample.  As with all bioinformatics pipelines, you might want to experiment with these features using a modest dataset to start such as a few BAMS that have been chrom selected (pick a small sequence for several samples).
