### ISSUE TITLE
FusorSV for Build38 data

### ISSUE THREAD

**Issue by lauracottino** [timothyjamesbecker/SVE#12]
Hi, 

We are having trouble getting FusorSV to run on Build38 data - SVE ran successfully but when we run FusorSV the resulting VCF file is empty. Is it possible to run it on Build38 data?

Thank you in advance.

**Comment by timothyjamesbecker** [comment]
This repo is for SVE, if you have a question or issue about the FusorSv part as indicated, you should put this same question in that other repo and I would be happy to answer.  Issues help other to see what is going on and working/not working in a repo and so this organization thing is important.  I look forward to your question in the FusorSV repo next door.
