### ISSUE TITLE
human_g1k_v37_decoy.fa Missing

### ISSUE THREAD

**Issue by 543090lee** [timothyjamesbecker/SVE#14]
Hello,
I pulled a docker image from the Github, and the data folder was empty, so I am downloading the files manually.
I couldn't find human_g1k_v37_decoy.fa on the github website. Where can I download this file?

Thank you

**Comment by timothyjamesbecker** [comment]
The file you are looking for is right in the user documentation for SVE. See section:  (1) Alignment of FASTQ and generation of BAM files
