### ISSUE TITLE
Normal/germline BAM?

### ISSUE THREAD

**Issue by brucemoran** [timothyjamesbecker/SVE#2]
Hi Timothy,

our early tests of SVE are good, very easy to work with. Wondering about support for germline/normal samples, have you considered this?

Thanks, Bruce.

**Comment by timothyjamesbecker** [comment]
Hello Bruce, did you mean tumor/normal samples?  If so, it has been considered and I am working words an alternate workflow that is similar to the auto.py script in that it would be able to process one tumor/normal sample thereby utilizing some additional mechanisms tailored for that purpose.

**Comment by brucemoran** [comment]
Hi, yes that is what I mean. Good to hear it is active, look forward to implementation. Bruce.
