### ISSUE TITLE
Joint calling vs. non-joint calling

### ISSUE THREAD

**Issue by jiangyuanluo** [timothyjamesbecker/SVE#3]
I saw that SVE lets BreakDancer, Hydra and cnMops do joint calling if there are several samples, but in the example each sample has a vcf file for each algorithm when fed into FusorSV. How does SVE separate the joint calling result? Can I run these algorithms without joint calling and feed into FusorSV?

**Comment by timothyjamesbecker** [comment]
Joint calling for SV callers usually will produce a single VCF file.  The exception is GenomeSTRiP 2 which will include which sample has which SV in which case we provide VCF separation measures under the GenomeSTRiP SVE stage. The SVE does not separate this result in its current form for other callers that are not able to provide the sample to call information.  So you can run this system on one sample using several callers and then achieve a better result than a single caller.
