### ISSUE TITLE
Tumor/normal samples and Can't connect mysql server

### ISSUE THREAD

**Issue by lh12565** [timothyjamesbecker/SVE#6]
Hi, I already have tumor/normal bam files. Can I call SV following this:

docker run -it -v /:/data timothyjamesbecker/sve /software/SVE/scripts/variant_processor.py\
-r /data/ref/human_g1k_v37_decoy.fa \
-b /data/rawData/multiLungCancer/WGS/Mapping/P1T1/P1T1.final.bam,/data/rawData/multiLungCancer/WGS/Mapping/P1N/P1N.final.bam \
-o /data/data1/P1_1/vcfs/ \
-s breakdancer,gatk_haplo,delly,lumpy,cnvnator

When I run this command, there is a error as below:

start():ER5.Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused)
query():ER10.Unknown_Error: 'NoneType' object has no attribute 'cursor'
__exit__():ER2.Unknown_Error: 'NoneType' object has no attribute 'close'

<<<<<<<<<<<<<USING HOST d02f0d880f5c>>>>>>>>>>>>>>>=

using reference name = Homo_sapiens_assembly38
start():ER5.Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused)
query():ER10.Unknown_Error: 'NoneType' object has no attribute 'cursor'
__exit__():ER2.Unknown_Error: 'NoneType' object has no attribute 'close'
unkown reference: run starting with -1
using ref_id=-1
start():ER5.Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused)
query():ER10.Unknown_Error: 'NoneType' object has no attribute 'cursor'
__exit__():ER2.Unknown_Error: 'NoneType' object has no attribute 'close'
starting run_id = None
processing bam list
['/data/rawData/multiLungCancer/WGS/Mapping/P1T1/P1T1.final.bam', '/data/rawData/multiLungCancer/WGS/Mapping/P1N/P1N.final.bam']
---------------running stats and conditional cleaning-------------------
loaded param_map from: bam_stats.json
pickle length is 0.0 mega bytes
compressed pickle length is 0.0 mega bytes
start():ER5.Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused)
query():ER10.Unknown_Error: 'NoneType' object has no attribute 'cursor'
__exit__():ER2.Unknown_Error: 'NoneType' object has no attribute 'close'
using wrapper: bam_stats
/software/samtools-1.3/samtools stats /data/rawData/multiLungCancer/WGS/Mapping/P1T1/P1T1.final.bam | grep ^SN | cut -f 2-
pickle length is 0.0 mega bytes
compressed pickle length is 0.0 mega bytes
start():ER5.Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused)
query():ER10.Unknown_Error: 'NoneType' object has no attribute 'cursor'
__exit__():ER2.Unknown_Error: 'NoneType' object has no attribute 'close'

My program is still running, although there is nothing in top.
Can this error be ignored?

Thanks!

**Comment by timothyjamesbecker** [comment]
The SVE was designed to have an optional DB component that you can either use or not use.  If you have a local MySQL server instance running on or in contact with the compute unit that is running docker the SVEDB will keep track of runs as well as store variants etc.  It really is just a starting place to be able to make larger SV focused web services.  As such, the errors you are seeing are related only to the SVEDB.  GATK and Delly each perform local assembly and this can take a very long time to process large BAM files.  You should see some vcf files if everything is working and they will slowly be populated one at a time. For faster performance you could use several machines and give each one the command line above but use a single -s stage.  Additionally if you specify the depth and length a priori you will save an entire pass on the data:
-D 200 -L 250 would let the system know that the depth was 200 and read length was 250bp.

**Comment by lh12565** [comment]
Hi Timothy Becker,
I have already aligned FASTQ paired end reads to a reference genome and generated bam files before use your tools, so I didn't run prepare_ref.py and prepare_bam.py. Today I get a error below when I run the above command:

ERROR MESSAGE: Invalid argument value '/data/rawData/multiLungCancer/WGS/Mapping/P1N/P1N.final.bam' at position 10.

I wonder if there is a error in my command to run tumor/normal samples. Furthermore, the depth of my tumor and normal samples are different, so I don't know how to set the parameter of -D.

Thanks!

**Comment by timothyjamesbecker** [comment]
You have a comma separated list of bam files attached to the -b argument. Run each bam file separately and then you will be able to set the -D and -L parameters correctly.  Once calls are made if you use a tool like FusorSV to combine both samples you will be able to pick those calls that are assigned to the Tumor by using a tool like bcftools.  Let me know if that is what you are looking to do and I can try to provide the correct bcftools command.

**Comment by lh12565** [comment]
Hi Timothy Becker,
Some things have been delayed before. I have already run some samples without setting -D and -L before. In the step (2), you say "If -D or -L are left out, the bam_stats information gathering stage with determine this information for you", and I wonder if it is correct to run FusorSV without setting -D and -L in step (2).  Now, I already have two files: tumor.vcf and normal.vcf (paired), and I want to call somatic SV. How to use bcftools or something else to call somatic SV.

Thanks!
