### ISSUE TITLE
Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306'

### ISSUE THREAD

**Issue by yueyuanliu** [timothyjamesbecker/SVE#7]
Hi，
When I used the command "**python /software/SVE/scripts/prepare_ref.py -r /data/reference.fa -t breakseq:/software/SVE/data/ breakseq2_bplib_20150129.fna -o /data/ref/ -p 10**"，the error information appeared"**start():ER5.Unknown_Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306' (111 Connection refused)
query():ER10.Unknown_Error: 'NoneType' object has no attribute 'cursor'
__exit__():ER2.Unknown_Error: 'NoneType' object has no attribute 'close'"**，but it also can generate the corresponding files, and the files looks no problems. 
Will these error notifications affect the results? Can you help me resolve this problems? Thanks!

**Comment by timothyjamesbecker** [comment]
The SVEDB is an integrated database that was designed for working with large runs and monitoring the results from a cluster running many samples.  This database is a MySQL database and will attempt to utilize a configuration file and then try to log information to that DB host.  It will not affect any resulting tool usage but will help organize large runs numbers if needed.
